//V00009#学生档案表
WM.StudentRecordType=function(){
 var obj = new Object();
obj.Rid="0",
obj.Id="0",
obj.TeachingPlan="",
obj.Courseware="",
obj.Reflection="",
obj.Video="",
obj.TeachingSize="0",
obj.CoursewareSize="0",
obj.VideoSize="0",
obj.RefiectionSize="0",
obj.State="False",
obj.EndDateTime="2012/12/12 0:00:00",
obj.TypeName="",
obj.TeachingName="",
obj.CoursewareName="",
obj.ReflectionName="",
obj.VideoName="",
obj.TeachingPlanTime="2012/12/12 0:00:00",
obj.CoursewareTime="2012/12/12 0:00:00",
obj.ReflectionTime="2012/12/12 0:00:00",
obj.VideoTime="2012/12/12 0:00:00",
obj.Did="0",
obj.TeacherTypeId="0",
obj.Number="0",
obj.College="",
obj.School="",
obj.StudentName="",
obj.StudentLoginId="",
obj.Disable="False",
obj.Apply="False",
obj.Model_Type="ALOS.Model.StudentRecordType",
obj.AppraisalNumber="0";
     return obj;
};
